dependencies:
- name: cbagogo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: emailchat-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: gohttps
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: goqsr
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
